---
title: "In Class"
author: "Haoran Zhang"
date: '2022-08-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x=4/52*3/51+48/52*4/51
y=4/52
x
y
```

```{r}
1-(1-1/6)^4
```


```{r}
nreps = 1000
set.seed(2022)
results = numeric(0)
for (i in 1:nreps) results[i] = any(sample(1:6, size = 4, replace = TRUE) == 6)
mean(results)
```
## 3i
```{r}
nreps = 1000
set.seed(2022)
results = numeric(0)
for (i in 1:nreps) results[i] = any(sample(1:6, size = 4, replace = TRUE) == 6)
mean(results)
```
## 3ii
$P=1-(1-\frac{1}{6})^4=0.518$ \

## 3iii
```{r}
diceRolls = replicate(2, sample(1:6, 24, replace = TRUE))
dice=NULL
results=NA
for (i in 1:nreps) {
  for (n in 1:24) {
    dice[n] = any(sample(1:6, size = 1, replace = TRUE) == 6)*any(sample(1:6, size = 1, replace = TRUE) == 6)
}
  results[i] = any(dice==1)
}
mean(results)
```
## 3iv
$1-(1-\frac{1}{6}\cdot\frac{1}{6})^{24}=

```{r}
diceRolls = replicate(2, sample(1:6, 24, replace = TRUE))
nreps = 10000
for (i in nreps) 
   dice[i] = any(for (j in 1:24) diceRolls[j,] == c(6,6))
mean(dice)
```


## 4

```{r}
nreps = 1000
set.seed(2022)
results = numeric(0)
for (i in 1:nreps) results[i] = any(duplicated(sample(1:365, size=23, replace=TRUE)) == TRUE)
mean(results)
```

```{r}
n=1
nreps = 1000
set.seed(2022)
results = numeric(0)
if(isTRUE(mean(results)<0.5))
  n=n+1
  for (i in 1:nreps) results[i] = any(duplicated(sample(1:365, size=n, replace=TRUE)) == TRUE)
  
```

```{r}
n=183
for (k in 2:365)
  for (i in nreps) 
```

```{r}
choose(23, 2) * choose(365, 21) / choose(365, 23)
```


```{r}
n=1
while (isTRUE(results[n]<0.5))
  n=n+1
  for (i in nreps) bday[i]=any(duplicated(sample(1:365, size=n, replace=TRUE)) == TRUE)
results[n]=mean(bday)
```


